# -*- coding: utf-8 -*-
"""coba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g5yONUAqCZXiSdhV3OogI9Rf54NcQQPZ
"""

from flask import Flask
app = Flask(__name__)
 
@app.route("/")

import math
print('Operasi Matematika')
print('  1. Jumlah \t [+]')
print('  2. Kurang \t [-]')
print('  3. Kali \t [*]')
print('  4. Bagi \t [/]')
print('  5. Faktorial \t [!]')
operasi = input('Pilih operasi (1/2/3/4/5): ')
bilangan_1 = eval(input('Masukkan bilangan pertama: '))
bilangan_2 = eval(input('Masukkan bilangan kedua: '))


if operasi == '1':
  hasil = bilangan_1 + bilangan_2
  print(f'Hasil operasi dari {bilangan_1} + {bilangan_2} = {hasil}')
elif operasi == '2':
  hasil = bilangan_1 - bilangan_2
  print(f'Hasil operasi dari {bilangan_1} - {bilangan_2} = {hasil}')
elif operasi == '3':
  hasil = bilangan_1 * bilangan_2
  print(f'Hasil operasi dari {bilangan_1} * {bilangan_2} = {hasil}')
elif operasi == '4':
  hasil = bilangan_1 / bilangan_2
  print(f'Hasil operasi dari {bilangan_1} / {bilangan_2} = {hasil}')
elif operasi =='5':
  faktorial = math.factorial(bilangan_1)
  print(f'{bilangan_1}! = {faktorial}')
else:
  print('Tidak valid')

if __name__ == "__main__":
    app.run()